Algoritmo "calculo de dobro"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/04/2026
Var
// Seção de Declarações das variáveis 
  num1, num2, num3:real
  resultado:real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("comprimento (em m3):")
leia(num1)
escreval("largura (em m3):")
leia(num2)
escreval("altura (em m3):")
leia(num3)

resultado <- num1*num2*num3

escreval("volume: ", resultado:2:1, "m3")
 
 Fimalgoritmo